### PR TITLE
Introduce proper handling for static calls

### LINKED ISSUE #5: Wrong Base-Reference for Static calls
for 
```java
private static byte[] setMasterPass(String mastPass, byte[] salt) throws IOException, NoSuchAlgorithmException {
        //Create new hash with SHA512
        MessageDigest md = MessageDigest.getInstance("SHA-512");
        ByteArrayOutputStream bout = new ByteArrayOutputStream();
        bout.write(salt);
        bout.write(mastPass.getBytes());
        return md.digest(bout.toByteArray());
    }
```
(MessageDigest.getInstance is a static Call)

the `base` of `getInstance` should not be `this`!

### PR DESCRIPTION
**Pull request by Masrepus**
Fixes #5

### CODE REVIEW

**Comment by oxisto** [comment]
Hmm can we somehow address this with the existing `MemberCallExpression` after all, it is still a call to a member of a class, is it not? Not quite sure what the `base` in this case would be. Hmm

**Comment by Masrepus** [comment]
I think the current definition of our `MemberCallExpression` treating it as a call to a function which is a "member of an object" should not be changed to "member of a class". Otherwise one could argue that basically all calls are somehow member calls, as each method is the member of a class. In the end I would still handle static calls as normal `CallExpressions`, as it is done here, with the added benefit that we can distinguish static calls from non-static ones in the call resolver

**Comment by oxisto** [comment]
I agree that the definition should not be changed. However, for example if you look at how Java reflect deals with static calls, it is still referring to the method/member of the class but then invoking this call with `null` instead of a reference to a particular object. 

I am not sure if we ever build the functionality on the CPG to retrieve the matching `MemberExpression` for a `MemberCallExpression`, it was my original intent to do so. But by looking at the current `MemberCallExpression` class, we might be able to get rid of it all together and just have a `CallExpression`

**Comment by Masrepus** [comment]
Merging them all into `CallExpression` sounds like a good idea on the longer term

**Pull request merged**
