### PR TITLE
Adding EOG edge building pass as subvariant of the current eog pass t…

### PR DESCRIPTION
**Pull request by konradweiss**
…hat connects some language structures differently. Structures like if, for, switch, synchronized have an expression that needs to be evaluated first and these are now connected to the root node of the expression before the eog connects the 'body' this allows to parse the expression and then deduce its meaning from the following node that is the root node and thus gives information on the semantic of the overal language structue.

### CODE REVIEW

**Comment by oxisto** [comment]
What is the reasoning behind having two passes now?

**Comment by JulianSchuette** [comment]
> What is the reasoning behind having two passes now?

I'll test it and if it's correct and does not fail the existing analyses, we'll migrate to only this new pass.

**Comment by JulianSchuette** [comment]
Looks good to me, at least for `IfStatement`. I would propose to replace the current EOG pass with this variant, so it will also become part of `defaultPasses()`.

**Comment by oxisto** [comment]
Yes, please combine it into one pass @konradweiss

**Comment by JulianSchuette** [comment]
Ah, well. The graph itself looks good, but the tests are still NOK. This needs to be fixed first:

_DemoTests.testHierarchy()_:
```
java.lang.StackOverflowError
	at java.base/java.lang.Class.getSimpleName(Class.java:1550)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.pushToEOG(EvaluationOrderGraphPass.java:786)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.java:594)
	at de.fraunhofer.aisec.cpg.passes.BranchSemanticEOGPass.handleConditionalExpression(BranchSemanticEOGPass.java:39)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.java:574)
	at de.fraunhofer.aisec.cpg.passes.BranchSemanticEOGPass.handleConditionalExpression(BranchSemanticEOGPass.java:40)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.java:574)
	at de.fraunhofer.aisec.cpg.passes.BranchSemanticEOGPass.handleConditionalExpression(BranchSemanticEOGPass.java:40)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.java:574)
	at de.fraunhofer.aisec.cpg.passes.BranchSemanticEOGPass.handleConditionalExpression(BranchSemanticEOGPass.java:40)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.java:574)
	at de.fraunhofer.aisec.cpg.passes.BranchSemanticEOGPass.handleConditionalExpression(BranchSemanticEOGPass.java:40)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.java:574)
	at de.fraunhofer.aisec.cpg.passes.BranchSemanticEOGPass.handleConditionalExpression(BranchSemanticEOGPass.java:40)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.java:574)
	at de.fraunhofer.aisec.cpg.passes.BranchSemanticEOGPass.handleConditionalExpression(BranchSemanticEOGPass.java:40)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.java:574)
	at de.fraunhofer.aisec.cpg.passes.BranchSemanticEOGPass.handleConditionalExpression(BranchSemanticEOGPass.java:40)
...
```

Also, both test cases in _JavaVsCppTest_ need to be adapted and I am unsure if this order is actually correct:
```
0 Literal
1 VariableDeclaration
2 DeclarationStatement
3 DeclaredReferenceExpression
4 Literal
5 BinaryOperator
6 IfStatement
7 DeclaredReferenceExpression
8 DeclaredReferenceExpression
9 DeclaredReferenceExpression
10 CallExpression
11 BinaryOperator
12 ReturnStatement
13 CompoundStatement
```

**Pull request merged**
