### PR TITLE
Bump Kotlin to 2.0.20

### PR DESCRIPTION
**Pull request by maximiliankaul**

### CODE REVIEW

**Comment by oxisto** [comment]
Should we add the experimental UUID to the compiler options as well? It is specified in cpg.common-conventions.gradle:
```
freeCompilerArgs = listOf("-opt-in=kotlin.RequiresOptIn", "-opt-in=kotlin.uuid.ExperimentalUuidApi", "-Xcontext-receivers")
```

should do the trick

**Comment by maximiliankaul** [comment]
> Should we add the experimental UUID to the compiler options as well? It is specified in cpg.common-conventions.gradle:
> 
> ```
> freeCompilerArgs = listOf("-opt-in=kotlin.RequiresOptIn", "-opt-in=kotlin.uuid.ExperimentalUuidApi", "-Xcontext-receivers")
> ```
> 
> should do the trick

I currently annotate the function I'm using UUID in.
Both works for me.

**Comment by oxisto** [comment]
> > Should we add the experimental UUID to the compiler options as well? It is specified in cpg.common-conventions.gradle:
> > ```
> > freeCompilerArgs = listOf("-opt-in=kotlin.RequiresOptIn", "-opt-in=kotlin.uuid.ExperimentalUuidApi", "-Xcontext-receivers")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > should do the trick
> 
> I currently annotate the function I'm using UUID in. Both works for me.

I would prefer the opt-in module, then I can also replace the other code where I am currently using the java UUID.

**Comment by maximiliankaul** [comment]
> > > Should we add the experimental UUID to the compiler options as well? It is specified in cpg.common-conventions.gradle:
> > > ```
> > > freeCompilerArgs = listOf("-opt-in=kotlin.RequiresOptIn", "-opt-in=kotlin.uuid.ExperimentalUuidApi", "-Xcontext-receivers")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > should do the trick
> > 
> > 
> > I currently annotate the function I'm using UUID in. Both works for me.
> 
> I would prefer the opt-in compiler flag, then I can also replace the other code where I am currently using the java UUID.

I'll add this to https://github.com/Fraunhofer-AISEC/cpg/pull/1728

**Review by oxisto — APPROVED** [review]

**Pull request merged**
