### PR TITLE
Fix leaking types

### PR DESCRIPTION
**Pull request by JulianSchuette**
There is one major problem and a few minor ones with the TypeManager:
The major problem is that the singleton instance of TypeManager keeps lists of Types. These Types may refer to RecordDeclarations (including the whole AST of a source file) and were never removed from memory. This is not only a memory leak but also messes up later analysis runs.

The minor problems are related to unclear nullability of fields and the fact that unit tests call TranslationManager.analyze(), but expect that TypeManager is still populated afterwards (although it should in fact be cleaned up). Actually, tests are making false assumptions here.

### CODE REVIEW

**Comment by oxisto** [comment]
Looks like a merge conflict here? We got rid of the `disableCleanup` option and this is now done through mocking in unit tests.

**Comment by Masrepus** [comment]
Mocking away this reset behaviour works even though it is a static method, as the mock replaces the type manager instance. The corresponding trigger is `TestUtils.disableTypeManagerCleanup()`

**Comment by JulianSchuette** [comment]
> Mocking away this reset behaviour works even though it is a static method, as the mock replaces the type manager instance. The corresponding trigger is `TestUtils.disableTypeManagerCleanup()`

I tried that but `reset()` was not called. And this somehow makes sense because Mockito currently replaces the _instance_ , not the static implementation. A quick Google search told me that Mockito alone cannot do that properly but rather PowerMock had to be used.

So I went for the `disableCleanup` solution.

The underlying problem is that tests are expecting content in TypeManager to be available which actually should _not_ be available after the analysis. I guess the tests should be re-written in the longer term.

**Comment by Masrepus** [comment]
Ah, I just saw that there is a difference between reset and cleanup in the TypeManager. I think you should call cleanup from the type resolver, which is non-static and actually clears the type to record mapping as you want it to

**Comment by Masrepus** [comment]
In my opinion we should remove the static reset function and use the cleanup method instead

**Comment by JulianSchuette** [comment]
> Ah, I just saw that there is a difference between reset and cleanup in the TypeManager. I think you should call cleanup from the type resolver, which is non-static and actually clears the type to record mapping as you want it to

It was unclear to me why there is a `cleanup()` and a `reset()` method. But what we actually need is to clean these two lists:

```
  private Set<Type> firstOrderTypes = new HashSet<>();
  private Set<Type> secondOrderTypes = new HashSet<>();
```

`cleanup()` does not do that.

**Comment by Masrepus** [comment]
I see. It seems that when implementing the cleanup method I forgot to clear those as well

**Comment by oxisto** [comment]
Can we change the mocked method to clean those up as well then? I would prefer the mocked-solution to introducing a config parameter that is only used in tests.

**Comment by Masrepus** [comment]
Now I remember why there is a separate reset method. When a test mocks the TypeManager instance, the next test would also get the mock as the new instance. This is why before each test the TypeManager instance is reset to a fresh one. A better solution would probably be to remove this reset method, make the cleanup one really clean up all state, and then in the beforeEach test method to set the TypeManager instance to null, so that it is re-created as it should, upon first use

**Comment by JulianSchuette** [comment]
> Can we change the mocked method to clean those up as well then? I would prefer the mocked-solution to introducing a config parameter that is only used in tests.

TBH, I see this as a quick fix that I need to get Codyze up to date. In the longer term, there are some architectural smells that could be changed:

- `TypeManager` should not need to be a singleton. Singletons are prone to memory leaks, make CPG almost impossible to use in multi-threaded applications, and add complexity (see the cleanup/reset problem).
- Most CPG nodes access the TypeManager singleton in their `typeChanged` method. This tightly couples the CPG nodes to the specific TypeManager. This type of logic should reside outside of the actual CPG, maybe in some visitor.
- Tests should test for the expected behavior and not use reflection magic to inject slightly manipulated objects into TypeResolver at runtime. Either we should have tests that call `TranslationManager.analyze()` - they should expect that everything is cleaned up afterwards. When testing the `TypeManager` itself, tests should create an instance of it and feed it (dummy) data to check if it behaves correctly.

**Comment by Masrepus** [comment]
That's true, although I'm currently unsure how the correct type behavior can be realized without a global singleton "supervisor", e.g. setting the type of a node to the lowest common supertype of all possible subtypes. Maybe inside a very early pass, e.g. the TypeHierarchyResolver?

Concerning the tests, you're right that they should test the type manager on its own, with dummy data

**Comment by JulianSchuette** [comment]
Ah, seems like there are some more broken parts now, possibly caused by the commits in this PR:

```
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at de.fraunhofer.aisec.cpg.graph.type.TypeParser.createFrom(TypeParser.java:715)
	at de.fraunhofer.aisec.cpg.frontends.cpp.DeclarationListHandler.handleSimpleDeclaration(DeclarationListHandler.java:71)
	at de.fraunhofer.aisec.cpg.frontends.cpp.DeclarationListHandler.lambda$new$0(DeclarationListHandler.java:52)
	at de.fraunhofer.aisec.cpg.frontends.Handler.handle(Handler.java:112)
	at de.fraunhofer.aisec.cpg.frontends.cpp.StatementHandler.handleDeclarationStatement(StatementHandler.java:267)
	at de.fraunhofer.aisec.cpg.frontends.cpp.StatementHandler.lambda$new$2(StatementHandler.java:53)
	at de.fraunhofer.aisec.cpg.frontends.Handler.handle(Handler.java:112)
	at de.fraunhofer.aisec.cpg.frontends.cpp.StatementHandler.handleCompoundStatement(StatementHandler.java:289)
	at de.fraunhofer.aisec.cpg.frontends.cpp.StatementHandler.lambda$new$0(StatementHandler.java:49)
	at de.fraunhofer.aisec.cpg.frontends.Handler.handle(Handler.java:112)
	at de.fraunhofer.aisec.cpg.frontends.cpp.StatementHandler.handleCatchHandler(StatementHandler.java:105)
	...
```

@Masrepus This is thrown when running `RealBotanTest.testArsenic()`.

**Comment by Masrepus** [comment]
That looks like a problem in the type parsing algorithm, @vfsrfs will know more about this I guess.
What was the String parsed there?

**Comment by JulianSchuette** [comment]
> That looks like a problem in the type parsing algorithm, @vfsrfs will know more about this I guess.
> What was the String parsed there?

Empty string.

**Comment by Masrepus** [comment]
Empty string or does it contain spaces? If it's the latter, I think the problem lies here, it is only checked whether the String has length 0 but not whether it only consists of whitespaces: https://github.com/Fraunhofer-AISEC/cpg/blob/ff3dd6d87437c2a2995f7a9a9c566be03041395d/src/main/java/de/fraunhofer/aisec/cpg/graph/type/TypeParser.java#L666-L669

**Comment by JulianSchuette** [comment]
> Empty string or does it contain spaces? If it's the latter, I think the problem lies here, it is only checked whether the String has length 0 but not whether it only consists of whitespaces:

Yes, that was one problem. It's fixed now.

Another problem is the type string `const` which comes from the source line `const auto error = QString{e.what()};`.

**Comment by JulianSchuette** [comment]
"Fixed" also that problem. What is the expected behavior of "auto" types? Seems like currently they are not supported. This PR now bails with an `UnknownType`. Is that intended?

Possibly related to issue #158

**Comment by Masrepus** [comment]
I would say unknown is correct, as the behavior is the same as a `var` in Java -> The type comes from the right hand side of the assignment and is thus correctly propagated if the left hand side is of type unknown

**Comment by JulianSchuette** [comment]
Yes, right. I just found this piece:

```
    if (finalType.getTypeName().equals("auto") || (type.contains("auto") && !primitiveType)) {
      // In C++17 if auto keyword is used the compiler infers the type automatically, hence we
      // are not able to find out, which type this should be, it will be resolved due to
      // dataflow
      return UnknownType.getUnknownType();
    }
```

**Comment by JulianSchuette** [comment]
Good, for the moment this PR should do the job. @konradweiss  would you merge it?

**Pull request merged**
