### PR TITLE
Improving CXX method resolution

### LINKED ISSUE #650: CallExpression is connected to wrong MethodDeclaration
In case the implementation of a method is not given, but a method with same name and same signature (but from a different class) exists, the `CallExpression` is connected to the wrong `MethodDeclaration` (via `INVOKES` edge).

Example:
```c++
class A {
public:
        void foo(int a);
};

class B {
public:
        void foo(int a);
};

void B::foo(int a) {
}

int main() {
        A a;
        B b;

        a.foo(1);
        b.foo(2);

        foo();

        C c;
        c.foo(3);
}
```

When loading the example c++ code into the cpg, all three calls of a method `foo` (`a.foo`, `b.foo`, `c.foo`) are connected to the `MethodDeclaration` of `B::foo`.

cpg_bug_CallExpression

### PR DESCRIPTION
**Pull request by oxisto**
This PR is a little bit of a hack that improves CXX method resolution for now, until we redesign the call resolver (see #704)

Fixes #650

### CODE REVIEW

**Comment by peckto** [comment]
Thanks a lot for this fix!
It works quite well. I just noticed a problem when resolving a method call, from an unknown class (eg. `c.foo(4)`).
In case a function with same name does exist, it is connected to this function, else no `INVOKES` edge is generated at all.

I added a test-case for the method resolution.

**Comment by oxisto** [comment]
> Thanks a lot for this fix! It works quite well. I just noticed a problem when resolving a method call, from an unknown class (eg. `c.foo(4)`). In case a function with same name does exist, it is connected to this function, else no `INVOKES` edge is generated at all.
> 
> I added a test-case for the method resolution.

I actually already had a test ready and just forgot to git add it. I have done this now, sorry for the override ;)

With regards to your "problem". This is intended. For your use case to produce an INVOKES edge to an inferred function of an inferred class, you need to modify the `InferenceConfiguration`. The default does not infer record declarations. The test shows how to enable this.

**Comment by peckto** [comment]
> With regards to your "problem". This is intended. For your use case to produce an INVOKES edge to an inferred function of an inferred class, you need to modify the `InferenceConfiguration`. The default does not infer record declarations. The test shows how to enable this.

Ok, that I didn't know.
But I'm still not sure about the case, when there is a `FunctionDeclaration` for `foo(int)` but not for `c.foo(int)`.
Regardless of the `inferenceConfiguration`, `c.foo(int)` is connected to `foo(int)`:
```cpp
void foo (int a) { }

int main() {
        foo(3);

        C c;
        c.foo(4);
}
```

image

**Comment by oxisto** [comment]
> > With regards to your "problem". This is intended. For your use case to produce an INVOKES edge to an inferred function of an inferred class, you need to modify the `InferenceConfiguration`. The default does not infer record declarations. The test shows how to enable this.
> 
> Ok, that I didn't know. But I'm still not sure about the case, when there is a `FunctionDeclaration` for `foo(int)` but not for `c.foo(int)`. Regardless of the `inferenceConfiguration`, `c.foo(int)` is connected to `foo(int)`:
> 
> ```c++
> void foo (int a) { }
> 
> int main() {
>         foo(3);
> 
>         C c;
>         c.foo(4);
> }
> ```
> 
> image

Ah, that should not be, I will check that.

**Comment by peckto** [comment]
Thanks for the fix!
Solves the issue for now.

**Pull request merged**
