### PR TITLE
Fixing StackoverflowException in `ScopeManager::getCurrentTypedefs`

### LINKED ISSUE #679: Stackoverflow Exception
Hi,
I encountered a Stackoverflow exception in the scope manager. Can't really reproduce it since it appears to occur more or less random to me.
```
Caused by: java.lang.StackOverflowError
        at java.util.Objects.equals(Objects.java:77) ~[?:?]
        at de.fraunhofer.aisec.cpg.graph.types.ObjectType.equals(ObjectType.java:181) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.passes.scopes.ScopeManager.getCurrentTypedefs$lambda-15(ScopeManager.kt:584) ~[cpg-core-master-SNAPSHOT.jar:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.noneMatch(ReferencePipeline.java:538) ~[?:?]
        at de.fraunhofer.aisec.cpg.passes.scopes.ScopeManager.getCurrentTypedefs(ScopeManager.kt:582) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.passes.scopes.ScopeManager.getCurrentTypedefs(ScopeManager.kt:581) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.passes.scopes.ScopeManager.getCurrentTypedefs(ScopeManager.kt:581) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.passes.scopes.ScopeManager.getCurrentTypedefs(ScopeManager.kt:581) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.passes.scopes.ScopeManager.getCurrentTypedefs(ScopeManager.kt:581) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.passes.scopes.ScopeManager.getCurrentTypedefs(ScopeManager.kt:100) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.TypeManager.resolvePossibleTypedef(TypeManager.java:741) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.types.TypeParser.createFromUnsafe(TypeParser.java:846) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.types.TypeParser.createFrom(TypeParser.java:887) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.TypeManager.lambda$getCommonType$10(TypeManager.java:492) ~[cpg-core-master-SNAPSHOT.jar:?]
        at java.util.Optional.map(Optional.java:265) ~[?:?]
        at de.fraunhofer.aisec.cpg.graph.TypeManager.getCommonType(TypeManager.java:492) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.TypeManager.isSupertypeOf(TypeManager.java:570) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.lambda$setType$1(Expression.java:147) ~[cpg-core-master-SNAPSHOT.jar:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.setType(Expression.java:148) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.BinaryOperator.typeChanged(BinaryOperator.java:200) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.lambda$setType$4(Expression.java:160) ~[cpg-core-master-SNAPSHOT.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.setType(Expression.java:160) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.DeclaredReferenceExpression.typeChanged(DeclaredReferenceExpression.java:145) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.lambda$setType$4(Expression.java:160) ~[cpg-core-master-SNAPSHOT.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.setType(Expression.java:160) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.BinaryOperator.typeChanged(BinaryOperator.java:200) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.lambda$setType$4(Expression.java:160) ~[cpg-core-master-SNAPSHOT.jar:?]
```
I guess thats a problem in the TypeManager or ScopeManager right?
I triggered that exception when parsing in the entire FFmpeg project and using UseParallelFrontend
Regards,
Tom

### PR DESCRIPTION
**Pull request by oxisto**
Converted `getCurrentTypedefs` to a while-loop instead of a recursion.

Fixes #679

### CODE REVIEW

**Comment by oxisto** [comment]
@anon767 Could you give this a try?

**Comment by oxisto** [comment]
> yes this seems to have fixed the issue :)

Perfect. A quick look of @konradweiss would be good, if I have captured the semantic of the previous implementation.

**Comment by anon767** [comment]
Hmm Im sorry but it seems like the problem still occurs just not as often anymore:

```
Caused by: java.lang.StackOverflowError
        at java.util.HashMap.hash(HashMap.java:339) ~[?:?]
        at java.util.HashMap.put(HashMap.java:607) ~[?:?]
        at java.util.HashSet.add(HashSet.java:220) ~[?:?]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.setPossibleSubTypes(Expression.java:177) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.ArraySubscriptionExpression.possibleSubTypesChanged(ArraySubscriptionExpression.java:98) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.lambda$setPossibleSubTypes$7(Expression.java:198) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.setPossibleSubTypes(Expression.java:198) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.BinaryOperator.possibleSubTypesChanged(BinaryOperator.java:220) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.lambda$setPossibleSubTypes$7(Expression.java:198) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.setPossibleSubTypes(Expression.java:198) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.HasType.setPossibleSubTypes(HasType.java:68) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.setType(Expression.java:155) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.DeclaredReferenceExpression.typeChanged(DeclaredReferenceExpression.java:145) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.lambda$setType$4(Expression.java:160) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.setType(Expression.java:160) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.BinaryOperator.typeChanged(BinaryOperator.java:200) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.lambda$setType$4(Expression.java:160) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
```

**Comment by anon767** [comment]
Alright :)

**Review by konradweiss — APPROVED** [review]
I had to understand the old code first as it is really complicated :D I did not implement it, but if I understood correctly the new version does the same and is a lot more readable @anon767 I think there is no specific issue related to your problem. A new one is very welcome

**Pull request merged**
