### PR TITLE
Add partial support for Control Flow Sensitive DFG

### PR DESCRIPTION
**Pull request by vfsrfs**
Addresses the missing Control Flow Sensitivity of the DFG mentioned in #95, by modifying ingoing and outgoing DFG edges in VariableDeclarations. This does not include Control Flow Sensitivity for FieldDeclarations, as their value might be modified at other locations, not necessarily in the analyzed method. SwitchStatements are supported, but they are trated as if they were always mutually exclusive. Mutual exclusion is not guaranteed, as fall throughs may occur.  In order to incorporate this behavior it is first necessary to be able to obtain the order to the CaseStatemtns, to know the target of a fall through.

Before (#95):
dfg1

After:
dfg2

Code:
```java
public class Main {
  void func() {
    int a = 1;
    if (args.length > 3) {
      a = 2;
    } else {
      System.out.println(a);
    }
  }
}

```

### CODE REVIEW

**Comment by oxisto** [comment]
Why is there a DFG node from "1" which is part of the `a=1` to the reference `a` that is part of the if - and no references to the variable declaration?

**Comment by Masrepus** [comment]
That's the modification that was desired to get controlflow sensitive behavior: We don't want value flow to show up at sinks that would never actually be able to see it, e.g. if it happens in mutually exclusive if else branches. So we either need to split up the variable declarations in kind of a single static assignment form, or we modify the DFG edges directly and don't go over the variable declaration. The last approach was the one that was chosen as it stays more true to the actual code graph

**Comment by oxisto** [comment]
@vfsrfs Could you update the picture above with how it will look like after we would merge this? Probably easier to see visually if we are "happy" with the DFG nodes.

**Comment by vfsrfs** [comment]
This PR addresses partial Control Flow Sensitive DFG by modifying ingoing and outgoing DFG edges in VariableDeclarations. If it is not possible to create a more refined DFG, the current DFG edges are not modified. Control Flow Sensitive DFG supports IfStatements and Switchstatements (including Fallthrough).

### Example

#### Code
```java
public class Main {
  void func() {
    int a = 1;
    if (args.length > 3) {
      a = 2;
    } else {
      System.out.println(a);
    }
  }
}
```

#### New Graph
newdfg



## Graph-Changes
### Added

- If mutually exclusive DFG flows are identified, DFG edges from the original node where the DFG flow begins (e.g. LiteralNode) to the DeclaredReferenceExpression where it is used are added.

### Removed

- If we can identify mutually exclusive DFG flows, outgoing DFG edges from the VariableDeclaration to the DeclaredReferenceExpression, where the variable is used, are removed.

## Interface-Changes
None

**Pull request merged**
