### PR TITLE
Trying to mitigate a CXX ambiguity in CDT that leads to a crash

### PR DESCRIPTION
**Pull request by oxisto**
This PR tries to mitigate #648 by making the EOG pass more robust as well as trying to recognize a certain CXX ambiguity (a call expression mistaken as a function declaration) by returning a problem declaration instead. This should at least not destroy the remaining AST scopes as it did before.

### CODE REVIEW

**Comment by oxisto** [comment]
@xaviergeorge can you have a look at this?

**Comment by xaviergeorge** [comment]
@oxisto  I found that this error was not reported(before your commit) when  
```
   // analyze the body
    if (funcDecl.hasBody()) {
      createEOG(funcDecl.getBody());
    }

    var currentScope = lang.getScopeManager().getCurrentScope();  
```
in the file `cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.java` inside the function `handleFunctionDeclaration` was changed to 
```
var currentScope = lang.getScopeManager().getCurrentScope();
// analyze the body
    if (funcDecl.hasBody()) {
      createEOG(funcDecl.getBody());
    }
    

```
The value of the `currentScope` was changed when `funcDecl.hasBody()` was true. In our case, when `srand(time(null))` was processed. Do you think it should be declared earlier or is it another bug?

**Comment by oxisto** [comment]
> @oxisto I found that this error was not reported(before your commit) when
> 
> ```
>    // analyze the body
>     if (funcDecl.hasBody()) {
>       createEOG(funcDecl.getBody());
>     }
> 
>     var currentScope = lang.getScopeManager().getCurrentScope();  
> ```
> 
> in the file `cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.java` inside the function `handleFunctionDeclaration` was changed to
> 
> ```
> var currentScope = lang.getScopeManager().getCurrentScope();
> // analyze the body
>     if (funcDecl.hasBody()) {
>       createEOG(funcDecl.getBody());
>     }
>     
> ```
> 
> The value of the `currentScope` was changed when `funcDecl.hasBody()` was true. In our case, when `srand(time(null))` was processed. Do you think it should be declared earlier or is it another bug?

Yes, the value of `currentScope` changed after the body was parsed because our CPP parser thought that `srand(time(null))` was a function declaration (inside a class, making it a method declaration). Therefore, the scope was changed to the current record by parsing the function body of `getRand`. This PR mitigates this problem by detecting this ambiguity and changing it to a `ProblemDeclaration`. This way the scope should stay the same.

**Comment by xaviergeorge** [comment]
> > @oxisto I found that this error was not reported(before your commit) when
> > ```
> >    // analyze the body
> >     if (funcDecl.hasBody()) {
> >       createEOG(funcDecl.getBody());
> >     }
> > 
> >     var currentScope = lang.getScopeManager().getCurrentScope();  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in the file `cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/EvaluationOrderGraphPass.java` inside the function `handleFunctionDeclaration` was changed to
> > ```
> > var currentScope = lang.getScopeManager().getCurrentScope();
> > // analyze the body
> >     if (funcDecl.hasBody()) {
> >       createEOG(funcDecl.getBody());
> >     }
> >     
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The value of the `currentScope` was changed when `funcDecl.hasBody()` was true. In our case, when `srand(time(null))` was processed. Do you think it should be declared earlier or is it another bug?
> 
> The value of `currentScope` changed after the body was parsed because our CPP parser thought that `srand(time(null))` was a function declaration (inside a class, making it a method declaration). Therefore, the scope was changed to the current record by parsing the function body of `getRand`. This PR mitigates this problem by detecting this ambiguity and changing it to a `ProblemDeclaration`. This way the scope should stay the same.
> 
> I would intentionally check the current scope after the EOG body parsing to detect similar problems in the future. I have added another check, if the scope is really a `FunctionScope`. The crash before resulted in a non-checked cast of the scope.

Okay. The branch works perfect with the file from the abyss project.

**Pull request merged**
