### PR TITLE
Convert Neo4j pre-save hooks to cpg pass

### PR DESCRIPTION
**Pull request by peckto**
In preparation for #1215

### CODE REVIEW

**Review by oxisto — COMMENTED** [review]
Looks good. Maybe just a quick discussion: Should we have this pass in `cog-core` or in `cpg-neo4j`?

**Comment by oxisto** [comment]
Ok it seems are test design for neo4j is really ... crap. We are setting up our own translation result here in the test instead of re-using the function that exists in the `Application`:

https://github.com/Fraunhofer-AISEC/cpg/blob/182b9ec991e484db543296c2f2fc5e37968c5c27/cpg-neo4j/src/test/kotlin/de/fraunhofer/aisec/cpg_vis_neo4j/ApplicationTest.kt#L47-L62

@peckto Can you maybe merge this as part of this PR so that the test is actually using the prepared TR of the application?

**Review by oxisto — APPROVED** [review]

**Comment by peckto** [comment]
I reworked the `ApplicationTest` to use the `setupTranslationConfiguration`, including the arg parse interface.

**Comment by peckto** [comment]
> Looks good. Maybe just a quick discussion: Should we have this pass in `cog-core` or in `cpg-neo4j`?

I don't have a strong opinion on this.
Maybe the pass is (in future) also helpful for other serialization methods?
We could also rename the pass to something more generic like `PrepareSerialization` or similar.

**Comment by peckto** [comment]
The pass is executed before `FilenameMapper`, as `FilenameMapper` is last, this will be second last.

**Comment by oxisto** [comment]
> > Looks good. Maybe just a quick discussion: Should we have this pass in `cog-core` or in `cpg-neo4j`?
> 
> I don't have a strong opinion on this. Maybe the pass is (in future) also helpful for other serialization methods? We could also rename the pass to something more generic like `PrepareSerialization` or similar.

Renaming it to `PrepareSerialization` would be a good idea.

**Review by oxisto — APPROVED** [review]

**Pull request merged**
